{
 "title": "Docker swarm cAdvisor dashboard",
 "tags": [
  "docker",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, job)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(swarm_node_info,job)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,container_label_com_docker_swarm_service_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{name=~\"$name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{name=~\"$name\",instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) * 100) by (instance) / sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)) / sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Whatsapp server status",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "/session/status/DISC_WPP_SESSION",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "CPU Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_cpu_user_seconds_total{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\",image!=\"\"} - container_memory_cache{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\",image!=\"\"})",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "I/O Tx:sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_fs_writes_bytes_total{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
       "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
      }
     ]
    },
    {
     "title": "I/O Rx:sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_fs_reads_bytes_total{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
       "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
      }
     ]
    },
    {
     "title": "Network Tx:sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Network Rx:sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"$name\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}