services:
  netbootxyz:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: "1"
          memory: 256M
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_SETUID
      - CAP_CHOWN
    environment:
      - PUID=1000
      - PGID=1000
      - SUBFOLDER=/
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
      - PORT_RANGE=30000:30010
      - TZ=America/Sao_Paulo
    volumes:
      - ./netbootxyz-config:/config
      - /mnt/truenas/netbootxyz:/assets # CIFS
    ports:
      - 9100:80
      - 9200:3000
      - mode: host
        protocol: udp
        published: 69
        target: 69
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true