{
 "title": "OPNSense",
 "description": "OPNSense metrics",
 "tags": [
  "opnsense",
  "firewall"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } },
   { "name": "wan_interface_1", "label": "WAN Interface 1", "query": { "query": "label_values(device)" } },
   { "name": "lan_interface_1", "label": "LAN Interface 1", "query": { "query": "label_values(device)" } },
   { "name": "fs_type", "label": "Filesystem Type", "query": { "query": "label_values(fstype)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$scrape_jobs\"} - node_boot_time_seconds{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{job=\"$scrape_jobs\"} - node_memory_swap_used_bytes{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_exec_forks_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Forks"
    },
    {
     "expr": "node_exec_system_calls_total{job=\"$scrape_jobs\"}",
     "legendFormat": "System Calls"
    },
    {
     "expr": "node_exec_traps_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$scrape_jobs\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"$scrape_jobs\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"$scrape_jobs\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$scrape_jobs\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{job=\"$scrape_jobs\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"$scrape_jobs\"} + node_memory_inactive_bytes{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_exec_device_interrupts_total{job=\"$scrape_jobs\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$scrape_jobs\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{job=\"$scrape_jobs\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "WAN 1 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_buffer_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_free_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_laundry_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Laundry"
    }
   ]
  },
  {
   "title": "WAN 1 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_swap_in_bytes_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"$scrape_jobs\"} - node_memory_swap_in_bytes_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "WAN 1 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$scrape_jobs\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$scrape_jobs\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  }
 ]
}