services:
  corsbypass:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.1'
          memory: 200M
        reservations:
          cpus: '.01'
          memory: 30M
    ports:
      - 9090:9090/tcp
    image: docker.io/aleixolucas/corsbypass
    environment:
      TZ: America/Sao_Paulo
    networks:
      - swarm-net
    restart: unless-stopped
networks:
  swarm-net:
    external: true
