services:
  adguardexporter:
    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.5'
          memory: 512M
        reservations:
          cpus: '.01'
          memory: 50M
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_NET_BIND_SERVICE
    container_name: adguard_exporter
    environment:
      - TZ=America/Sao_Paulo
      - ADGUARD_SERVERS=adguardhome_adguardhome
      - ADGUARD_USERNAMES=
      - ADGUARD_PASSWORDS=
    restart: unless-stopped
    networks:
      - swarm-net
networks:
  swarm-net:
    attachable: true
    external: true
