version: '3.8'
services:
  jenkins:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: "2"
          memory: 1024M
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
    environment:
      - TZ=America/Sao_Paulo
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 9000:8080
      # - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
volumes:
  jenkins_configuration:
    driver: local