version: '3.8'
services:
  bookstack:
    networks:
      - swarm-net
    environment:
      - DB_HOST=
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
      - APP_URL=
    ports:
      - 8080:8080
    container_name: bookstack_22.04
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.2'
          memory: 300M
        reservations:
          cpus: '.01'
          memory: 50M
    image: solidnerd/bookstack:22.04
networks:
  swarm-net:
    external: true