global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker_host
    static_configs:
      - targets: ["10.11.12.210:9323"]

  - job_name: cadvisor_container
    static_configs:
      - targets: ["swarm-prom-stack_cadvisor:8080"]

  - job_name: pve-exporter
    metrics_path: '/pve'
    static_configs:
    - targets:
      - pve-exporter_prometheus-pve-exporter:9221
    params:
      target: [10.11.12.253]

  - job_name: 'opnsense-native'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - 10.11.12.254:9100

  - job_name: duplicati_backup
    honor_labels: true
    scrape_interval: 10m
    scrape_timeout: 1m
    static_configs:
    - targets: ['duplicati-prometheus-exporter_duplicati-prometheus-exporter:5000']