global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker_host
    static_configs:
      - targets: ["10.11.12.210:9323"]

  - job_name: cadvisor_container
    static_configs:
      - targets: ["swarm-prom-stack_cadvisor:8080"]