version: '3.8'
services:
  adguardhome:
    image: adguard/adguardhome
    deploy:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.5'
          memory: 512M
        reservations:
          cpus: '.01'
          memory: 50M
    container_name: adguardhome
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    volumes:
      - work:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
    ports:
      - 8500:80/tcp
      - 53:53/tcp
      - 53:53/udp
    networks:
      - swarm-net
networks:
  swarm-net:
    attachable: true
    external: true
volumes:
  work:
    driver: local
  config:
    driver: local