services:
  adguardhome:
    image: adguard/adguardhome
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.5'
          memory: 512M
        reservations:
          cpus: '.01'
          memory: 50M
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_NET_BIND_SERVICE
    container_name: adguardhome
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    volumes:
      - work:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
    ports:
      - 8500:80/tcp      
      - mode: host
        protocol: tcp
        published: 53
        target: 53
      - mode: host
        protocol: udp
        published: 53
        target: 53
    networks:
      - swarm-net
networks:
  swarm-net:
    attachable: true
    external: true
volumes:
  work:
    driver: local
  config:
    driver: local
