services:
  whatsapp:
    healthcheck:
      test: ["CMD", "sh", "-c", "rm -f /usr/src/app/sessions/SingletonLock || true; echo ok"]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 10.11.12.210
      - 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.8'
          memory: 1024M
        reservations:
          cpus: '.1'
          memory: 256M
    cap_drop:
      - ALL
    container_name: whatsapp_web_api
    image: chrishubert/whatsapp-web-api:v1.26.0
    environment:
      # - API_KEY=your_global_api_key_here  # OPTIONAL
      - BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE
      - MAX_ATTACHMENT_SIZE=9000000
      - SET_MESSAGES_AS_SEEN=FALSE
      - DISABLED_CALLBACKS=message_ack
      - ENABLE_SWAGGER_ENDPOINT=TRUE
      - TZ=America/Sao_Paulo
    networks:
      - swarm-net
    ports:
      - 8700:3000/tcp
    volumes:
      - ./sessions:/usr/src/app/sessions

  discord_bot:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.05'
          memory: 50M
        reservations:
          cpus: '.1'
          memory: 10M
    cap_drop:
      - ALL
    environment:
      - TZ=America/Sao_Paulo
    image: aleixolucas/whatsapp_discord_bot
    container_name: discord_bot
    environment:
      - DISC_TOKEN=
      - CHAT_ID=
    networks:
      - swarm-net
    depends_on:
        - whatsapp
networks:
  swarm-net:
    external: true
