version: "3.8"
services:
  cadvisor:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - ./cAdvisor.yml:/etc/prometheus/prometheus.yml:ro
    container_name: cadvisor
    privileged: true
    networks:
      - swarm-net
    devices:
      - /dev/kmsg
    image: gcr.io/cadvisor/cadvisor
  prometheus:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
    container_name: my-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true