services:
  cadvisor:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
    cap_drop:
      - ALL
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - ./cAdvisor.yml:/etc/prometheus/prometheus.yml:ro
    container_name: cadvisor
    privileged: true
    networks:
      - swarm-net
    devices:
      - /dev/kmsg
    environment:
      - TZ=America/Sao_Paulo
    image: gcr.io/cadvisor/cadvisor
  prometheus:
    dns:
      - 10.11.12.210
      - 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
    cap_drop:
      - ALL
    container_name: my-prometheus
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8300:9090/tcp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
