global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files:

scrape_configs:

  - job_name: 'speedtest-exporter'
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ['speedtest-exporter_speedtest-exporter:9798']

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker_host
    static_configs:
      - targets: ["10.11.12.210:9323"]

  - job_name: cadvisor_container
    static_configs:
      - targets: ["swarm-prom-stack_cadvisor:8080"]

  - job_name: pve-exporter
    metrics_path: '/pve'
    static_configs:
    - targets:
      - pve-exporter_prometheus-pve-exporter:9221
    params:
      target: [10.11.12.253]

  - job_name: 'opnsense-native'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - 10.11.12.254:9100

  - job_name: duplicati_backup
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
    - targets: ['duplicati-prometheus-exporter_duplicati-prometheus-exporter:5000']

  - job_name: loki_swarm
    honor_labels: true
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets: ['loki_loki:3100']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 2m
    scrape_timeout: 2m
    static_configs:
      - targets:
        - https://cardsgo.ddns.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115

  - job_name: 'blackbox_http_internal_swarm_services'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 2m
    scrape_timeout: 2m
    static_configs:
      - targets:
        - http://adguard-exporter_adguard-exporter
        - http://adguardhome_adguardhome
        - http://audiobookshelf_audiobookshelf
        - http://blackbox-prom-exporter_blackbox-exporter
        - http://cardsgo_cardsgo
        - http://discord_wpp_bot_whatsapp_discord_bot
        - http://discord_wpp_bot_whatsapp_whatsapp
        - http://duplicati-prometheus-exporter_duplicati-prometheus-exporter
        - http://grafana2whatsapp_grafana2whatsapp
        - http://grafana_grafana
        - http://hashicorp-vault_vault
        - http://jenkins_jenkins
        - http://leo-intentio-api_intentio-api
        - http://leo-planit-api_planit-api
        - http://loki_loki
        - http://m5-stick-proxmox-metrics_m5-stick-proxmox-metrics
        - http://minecraft-server_mc
        - http://n8n_n8n
        - http://netbootxyz_netbootxyz
        - http://nginx_certbot
        - http://nginx_nginx
        - http://nginx_nginx_httpe2ban
        - http://ollama_open-webui_open-webui
        - http://ollama_wpp_integration_ollama_wpp_integration
        - http://pve-exporter_prometheus-pve-exporter
        - http://speedtest-exporter_speedtest-exporter
        - http://swarm-prom-stack_cadvisor
        - http://swarm-prom-stack_prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets:
        - 192.168.192.54
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115

  - job_name: 'adguard-exporter'
    static_configs:
      - targets: ['adguard-exporter_adguard-exporter:9618']

  - job_name: 'get_disc_wpp_session'
    metrics_path: /probe
    params:
      module: [get_disc_wpp_session]
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - http://discord_wpp_bot_whatsapp_whatsapp:3000/session/status/DISC_WPP_SESSION
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115
