global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker_host
    static_configs:
      - targets: ["10.11.12.210:9323"]

  - job_name: cadvisor_container
    static_configs:
      - targets: ["swarm-prom-stack_cadvisor:8080"]

  - job_name: pve-exporter
    metrics_path: '/pve'
    static_configs:
    - targets:
      - pve-exporter_prometheus-pve-exporter:9221
    params:
      target: [10.11.12.253]

  - job_name: 'opnsense-native'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets:
      - 10.11.12.254:9100

  - job_name: duplicati_backup
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
    - targets: ['duplicati-prometheus-exporter_duplicati-prometheus-exporter:5000']

  - job_name: loki_swarm
    honor_labels: true
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
    - targets: ['loki_loki:3100']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets:
        - https://cardsgo.ddns.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
      - targets:
        - 192.168.192.57
        - nutroclinic.ddns.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prom-exporter_blackbox-exporter:9115
