version: "3.4"

networks:
  swarm-net:
    external: true

volumes:
    loki-data:
      driver: pxd
      driver_opts:
        repl: 2
        size: 40

configs:
  loki_config:
    file: ./loki-local-config.yaml

services:
  loki:
    image: grafana/loki:v1.3.0
    command: -config.file=/etc/loki/loki-local-config.yaml
    configs:
      - source: loki_config
        target: /etc/loki/loki-local-config.yaml
    deploy:
      labels:
        prometheus.enable: "true"
        prometheus.port: "3100"
        prometheus.path: "/metrics"
      mode: replicated
      placement:
        constraints:
          - node.Labels.storagegroup==RED
      replicas: 1
    ports:
      - "3100:3100"
    networks:
      - swarm-net
    volumes:
      - loki-data:/data/loki