- job_name: 'nginx-controller'
  metrics_path: '/metrics'
  scrape_interval: 30s
  scrape_timeout: 20s
  static_configs:
  - targets:
    - ingress-nginx-controller.ingress-nginx.svc.cluster.local:10254
    - ingress-nginx-controller-admission.ingress-nginx.svc.cluster.local:10254
- job_name: 'opnsense-native'
  metrics_path: '/metrics'
  scrape_interval: 30s
  scrape_timeout: 20s
  static_configs:
  - targets:
    - 10.11.12.254:9100
- job_name: 'prometheus-pve-exporter'
  metrics_path: '/pve'
  scrape_interval: 30s
  scrape_timeout: 20s
  static_configs:
  - targets:
    - prometheus-pve-exporter-svc.prometheus-pve-exporter.svc.cluster.local:9221
  params:
    target: [10.11.12.253]
- job_name: 'adguard-exporter'
  static_configs:
  - targets: ['adguard-exporter-svc.adguard-exporter.svc.cluster.local:9617']