services:
  open-webui:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.4'
          memory: 512M
        reservations:
          cpus: '.01'
          memory: 50M
    ports:
      - 9300:8080
    environment:
      - OLLAMA_BASE_URL=http://10.11.12.245:11434
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    cap_drop:
      - ALL
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
volumes:
  open-webui:
   external: true
   name: open-webui
