version: '3.8'
services:
  nginx:
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-worker-oracle
      resources:
        limits:
          cpus: '.1'
          memory: 100M
        reservations:
          cpus: '.01'
          memory: 50M
    image: nginx
    container_name: nginx
    secrets:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
      - source: aleixohome_crt
        target: /etc/nginx/cert/aleixohome.crt
      - source: aleixohome_key
        target: /etc/nginx/cert/aleixohome.key
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
    networks:
      - swarm-net
    ports:
      - 80:80
      - 443:443
  certbot:
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-worker-oracle
    container_name: certbot
    depends_on:
        - nginx
    image: certbot/certbot:latest
    volumes:
    - certbot_www:/var/www/certbot/:rw
    - certbot_conf:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email aleixo1lucas@gmail.com -d cardsgo.ddns.net --agree-tos
    networks:
      - swarm-net
secrets:
  nginx_conf: #docker secret create nginx_conf nginx.conf
    external: true
  aleixohome_crt: #docker secret create aleixohome_crt aleixohome.crt
    external: true
  aleixohome_key: #dock
    external: true
networks:
  swarm-net:
    external: true
volumes:
  certbot_www:
    driver: local
  certbot_conf:
    driver: local