services:
  mc:
    dns:
      - 10.11.12.210
      - 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          memory: 2096M
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_SETGID
      - CAP_SETUID
    environment:
      EULA: "TRUE"
      ENABLE_WHITELIST: "true"
      VERSION: "1.21.5"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 5
      INIT_MEMORY: "1G"
      MAX_MEMORY: "2G"
      MEMORY: "2G"
      PVP: "false"
      SERVER_NAME: "homelab-minecraft-server"
      ENABLE_AUTOSTOP: "true"
      AUTOSTOP_TIMEOUT_INIT: 60
      AUTOSTOP_TIMEOUT_EST: 60
      AUTOSTOP_PERIOD: 7200
      TZ: "America/Sao_Paulo"
    volumes:
      - ./minecraft-data:/data
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
