services:
  mc:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          memory: 2096M
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 5
      PVP: "false"
      SERVER_NAME: "homelab-minecraft-server"
      MEMORY: "2G"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
    volumes:
      - ./minecraft-data:/data
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true