services:
  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-worker-oracle
      resources:
        limits:
          cpus: '.2'
          memory: 100M
        reservations:
          cpus: '.01'
          memory: 50M
    cap_drop:
      - ALL
    ports:
      - 9221:9221
    environment:
      - PVE_USER=user@pam/pve
      - PVE_PASSWORD=
      - PVE_VERIFY_SSL=
      - TZ=America/Sao_Paulo
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
