services:
  get-loc-python:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.5'
          memory: 1024M
        reservations:
          cpus: '.01'
          memory: 50M
    ports:
      - "9400:5000"
    environment:
      - PIPELINE_URL=
      - BASIC_AUTH=
    container_name: get-loc-python
    restart: always
    image: aleixolucas/get-loc-python
    cap_drop:
      - ALL
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
