          limits:
            memory: "512Mi"
            cpu: "200m"
---
automountServiceAccountToken: false
---
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seLinuxOptions: #conjunto de regras que dizem ao SELinux o que pode ou não ser acessado, para impor o acesso permitido por uma determinada política
            level: "s0:c123,c456"
          seccompProfile: #The default profiles aim to provide a strong set of security defaults while preserving the functionality of the workload
            type: RuntimeDefault
          capabilities: #https://man7.org/linux/man-pages/man7/capabilities.7.html^
            add:
            - SYS_NICE
            drop:
            - KILL
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-netpolicy
  namespace: mysql
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.0.0/24
  egress:           
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24