apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-in
  namespace: grafana
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/enable-opentracing: "jaeger-service-name"
spec:
  tls:
  - hosts:
    - grafana.aleixohome.lan
    secretName: aleixohome-ssl
  rules:
  - host: grafana.aleixohome.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-aleixohome
            port:
              number: 3000