version: '3.8'
services:
  duplicati-prometheus-exporter:
    deploy:
      update_config:
        order: start-first
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.2'
          memory: 90M
        reservations:
          cpus: '.1'
          memory: 10M
    cap_drop:
      - ALL
    container_name: duplicati-prometheus-exporter
    image: aleixolucas/duplicati-prometheus-exporter
    ports:
      - 8800:5000/tcp
    environment:
      - LOG_LEVEL=INFO
      - TZ=America/Sao_Paulo
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true
