apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstack-in
  namespace: bookstack
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - bookstack.aleixohome.lan
    secretName: aleixohome-ssl
  rules:
  - host: bookstack.aleixohome.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookstack
            port:
              number: 8080