version: '3.8'
services:
  nginx:
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-worker-oracle
      resources:
        limits:
          cpus: '.1'
          memory: 100M
        reservations:
          cpus: '.01'
          memory: 50M
    environment:
      - TZ=America/Sao_Paulo
    image: nginx
    container_name: nginx
    secrets:
      - source: nginx_main_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
      - type: bind
        source: /home/ubuntu/nginx/dbip4.dat #https://www.miyuru.lk/geoiplegacy
        target: /etc/nginx/country.dat
    networks:
      - swarm-net
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
  certbot:
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-worker-oracle
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 86400s
    container_name: certbot
    depends_on:
        - nginx
    image: certbot/certbot:latest
    volumes:
    - certbot_www:/var/www/certbot/:rw
    - certbot_conf:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --renew-by-default --email aleixo1lucas@gmail.com -d cardsgo.ddns.net --agree-tos
    networks:
      - swarm-net
secrets:
  nginx_main_conf: #docker secret create nginx_main_conf nginx_main.conf
    external: true
  nginx_conf: #docker secret create nginx_conf nginx.conf
    external: true
networks:
  swarm-net:
    external: true
volumes:
  certbot_www:
    driver: local
  certbot_conf:
    driver: local