version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.2'
          memory: 400M
        reservations:
          cpus: '.01'
          memory: 50M
    volumes:
      - data:/var/lib/grafana
    ports:
      - 8900:3000/tcp
    environment:
      - GF_SECURITY_ADMIN_USER=
      - GF_SECURITY_ADMIN_PASSWORD=
      - GF_SERVER_DOMAIN=grafana.aleixohome.lan
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
    secrets:
      - source: ldap_toml
        target: /etc/grafana/ldap.toml
    networks:
      - swarm-net
secrets:
  ldap_toml: #docker secret create ldap_toml ldap.toml
    external: true
networks:
  swarm-net:
    external: true
volumes:
  data:
    driver: local