apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardsgo-in-ext
  namespace: cardsgo
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      server_name cardsgo.ddns.net;

      ## OWASP 10017
      add_header Content-Security-Policy "default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; font-src 'self'; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cardsgo.ddns.net/ https://cdn.jsdelivr.net https://cdn.jsdelivr.net;";
      add_header Strict-Transport-Security "max-age=63072000";
      
      ## OWASP 10020
      add_header X-Frame-Options sameorigin;

      ## OWASP 10021
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "0; mode=block";

      ## Bloquear SQL injections
      set $block_sql_injections 0;
      if ($query_string ~ "union.*select.*\(") {
          set $block_sql_injections 1;
      }
      if ($query_string ~ "union.*all.*select.*") {
          set $block_sql_injections 1;
      }
      if ($query_string ~ "concat.*\(") {
          set $block_sql_injections 1;
      }
      if ($block_sql_injections = 1) {
          return 403;
      }

      ## Bloquear file injections
      set $block_file_injections 0;
      if ($query_string ~ "[a-zA-Z0-9_]=http://") {
          set $block_file_injections 1;
      }
      if ($query_string ~ "[a-zA-Z0-9_]=(\.\.//?)+") {
          set $block_file_injections 1;
      }
      if ($query_string ~ "[a-zA-Z0-9_]=/([a-z0-9_.]//?)+") {
          set $block_file_injections 1;
      }
      if ($block_file_injections = 1) {
          return 403;
      }

      ## Bloquear exploits comuns
      set $block_common_exploits 0;
      if ($query_string ~ "(<|%3C).*script.*(>|%3E)") {
          set $block_common_exploits 1;
      }
      if ($query_string ~ "GLOBALS(=|\[|\%[0-9A-Z]{0,2})") {
          set $block_common_exploits 1;
      }
      if ($query_string ~ "_REQUEST(=|\[|\%[0-9A-Z]{0,2})") {
          set $block_common_exploits 1;
      }
      if ($query_string ~ "proc/self/environ") {
          set $block_common_exploits 1;
      }
      if ($query_string ~ "mosConfig_[a-zA-Z_]{1,21}(=|\%3D)") {
          set $block_common_exploits 1;
      }
      if ($query_string ~ "base64_(en|de)code\(.*\)") {
          set $block_common_exploits 1;
      }
      if ($block_common_exploits = 1) {
          return 403;
      }

      ## Bloquear user agents
      set $block_user_agents 0;

      if ($http_user_agent ~ "Wget") {
          set $block_user_agents 1;
      }

      if ($http_user_agent ~ "Indy Library") {
          set $block_user_agents 1;
      }

      # Hoggers comuns de largura de banda e ferramentas de hacking.
      if ($http_user_agent ~ "libwww-perl") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "GetRight") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "GetWeb!") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "Go!Zilla") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "Download Demon") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "Go-Ahead-Got-It") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "TurnitinBot") {
          set $block_user_agents 1;
      }
      if ($http_user_agent ~ "GrabNet") {
          set $block_user_agents 1;
      }

      ## Block spam -> Achei na net
      set $block_spam 0;
      if ($query_string ~ "\b(ultram|unicauca|valium|viagra|vicodin|xanax|ypxaieo)\b") {
          set $block_spam 1;
      }
      if ($query_string ~ "\b(erections|hoodia|huronriveracres|impotence|levitra|libido)\b") {
          set $block_spam 1;
      }
      if ($query_string ~ "\b(ambien|blue\spill|cialis|cocaine|ejaculation|erectile)\b") {
          set $block_spam 1;
      }
      if ($query_string ~ "\b(lipitor|phentermin|pro[sz]ac|sandyauer|tramadol|troyhamby)\b") {
          set $block_spam 1;
      }
      if ($block_spam = 1) {
          return 403;
      }

      if ($block_user_agents = 1) {
          return 403;
      }
spec:
  tls:
  - hosts:
    - cardsgo.ddns.net
    secretName: cardsgo-tls
  rules:
  - host: cardsgo.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cardsgo
            port:
              number: 80