apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardsgo-in-ext
  namespace: cardsgo
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  tls:
  - hosts:
    - cardsgo.ddns.net
    secretName: cardsgo-tls
  rules:
  - host: cardsgo.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cardsgo
            port:
              number: 80