apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardsgo-in
  namespace: cardsgo
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - cardsgo.aleixohome.lan
    secretName: aleixohome-ssl
  rules:
  - host: cardsgo.aleixohome.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cardsgo
            port:
              number: 80