version: '3.8'
services:
  vault:
    deploy:
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.1'
          memory: 600M
        reservations:
          cpus: '.01'
          memory: 50M
    cap_drop:
      - ALL
    cap_add:
      - IPC_LOCK
      - CAP_SETFCAP
      - CAP_SETGID
      - CAP_SETUID
    environment:
      - 'VAULT_LOCAL_CONFIG={"storage": {"file": {"path": "/vault/file"}},
        "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable":
        true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h",
        "ui": true}'
      - TZ=America/Sao_Paulo
    image: hashicorp/vault
    command: server
    networks:
      - swarm-net
    ports:
      - 8100:8200/tcp
    volumes:
      - logs:/vault/logs
      - file:/vault/file
      - config:/vault/config
volumes:
  logs:
    driver: local
  file:
    driver: local
  config:
    driver: local
networks:
  swarm-net:
    external: true