version: '3.8'
services:
  cardsgo:
    container_name: cardsgo
    deploy:
      update_config:
        order: start-first
      placement:
        constraints:
          - node.hostname == fedora-swarm
      resources:
        limits:
          cpus: '.1'
          memory: 100M
        reservations:
          cpus: '.01'
          memory: 50M
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - database_psw=
      - database_user=
      - database_host=
      - TZ=America/Sao_Paulo
    image: aleixolucas/cardsgo
    ports:
      - 8400:5000
    networks:
      - swarm-net
networks:
  swarm-net:
    external: true