apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-in
  namespace: jaeger
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
spec:
  tls:
  - hosts:
    - jaeger.aleixohome.lan
    secretName: aleixohome-ssl
  rules:
  - host: jaeger.aleixohome.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-all-in-one
            port:
              number: 16686